# Generated by Django 5.1.15 on 2026-09-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name.', max_length=255)),
                ('role', models.CharField(help_text='Job title or role applied for.', max_length=255)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='wishlist', help_text='Current stage in the application pipeline.', max_length=20)),
                ('applied_date', models.DateField(blank=True, help_text='Date when application was submitted.', null=True)),
                ('job_url', models.URLField(blank=True, help_text='Link to the job posting.', max_length=500, null=True)),
                ('location', models.CharField(blank=True, help_text='Work location (e.g., Remote, Bengaluru, New York).', max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, help_text='Estimated or advertised salary (e.g., $80k-$100k or 8-12 LPA).', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal interview notes, contact persons, or preparation details.', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Date scheduled for sending a follow-up email.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'), models.Index(fields=['user', 'follow_up_date'], name='application_user_id_01d194_idx'), models.Index(fields=['user', '-created_at'], name='application_user_id_aaf56b_idx')],
            },
        ),
    ]
